# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/linux-64/args-0.1.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/asn1crypto-0.22.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/blas-1.1-openblas.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2017.7.27.1-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/certifi-2017.7.27.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cffi-1.10.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/chardet-3.0.2-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/clint-0.5.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cryptography-1.9-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/future-0.16.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/icu-58.1-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/idna-2.5-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libffi-3.2.1-3.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libgfortran-3.0.0-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libiconv-1.14-4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxml2-2.9.4-4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxslt-1.1.29-5.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/lxml-3.8.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/mkl-2017.0.3-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ncurses-5.9-10.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/nose-1.3.7-py36_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/numpy-1.12.1-py36_blas_openblas_200.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openblas-0.2.19-2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openssl-1.0.2l-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pandas-0.20.3-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pip-9.0.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pkginfo-1.4.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pycparser-2.18-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyface-5.1.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pygments-2.2.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyopenssl-16.2.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pysocks-1.6.7-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-3.6.2-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-dateutil-2.6.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pytz-2017.2-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyyaml-3.12-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/readline-6.2-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/requests-2.18.3-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/requests-toolbelt-0.8.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/setuptools-36.2.2-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/six-1.10.0-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sqlite-3.13.0-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tk-8.5.19-2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/traits-4.6.0-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/traitsui-5.1.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/twine-1.8.1-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/urllib3-1.21.1-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/wheel-0.29.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xz-5.2.2-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zlib-1.2.11-0.tar.bz2
